version: "3.0"
services:
  dockerapp:
    image: smalltides/dockerapp
    extends:
      file: common.yml
      service: dockerapp
  
  redis:
    extends:
      file: common.yml
      service: redis
